### ISSUE TITLE
Edit challenges, questions, objectives - Episode 10 - Functions

### ISSUE THREAD

**Issue by chennesy** [chennesy/lc-python-intro#15]
The challenges, questions, and objectives from [Episode 10](https://github.com/chennesy/lc-python-intro/blob/main/episodes/10-writing-functions.md) need to be edited and updated to reflect the episode content. Note that the challenges all use scientific examples, derived from the Software Carpentry gapminder Python lesson, and should be changed to connect better with a Library Carpentry audience.

**Comment by jt14den** [comment]
@chennesy, will work on this tomorrow. hope that won't mess up the prep for friday.

**Comment by chennesy** [comment]
PR #72 took care of this.
