### ISSUE TITLE
on list episode remove what we don't need later

### ISSUE THREAD

**Issue by jt14den** [chennesy/lc-python-intro#33]
I vote for only keeping what we need to use in later episodes on the list episode, e.g. "You can copy lists, but not using straightforward variable assignment" section seems weedy to me. We know learning facets of lists is important, but i'd keep to the basics of creating and adding.

**Comment by chennesy** [comment]
Related: consolidate discussions about basic operations (e.g., slicing, indexing) in Variables episode, when introducing strings, and then briefly mention how they apply to lists without re-explaining the concept in depth.
