### ISSUE TITLE
Create episode on data viz + tidy data

### ISSUE THREAD

**Issue by chennesy** [chennesy/lc-python-intro#4]
After introducing conditionals (episode 09) and functions (10 and 11), there should be an episode that pulls these concepts all together and uses loops, conditionals, and functions to operate on the library usage datasets.

**Comment by chennesy** [comment]
@jt14den Not assigning this to you, but just a heads up as you review Episodes 08 - 10, that I've noted that something that is missing is some content to apply what learners have used about loops, conditionals, and functions on the usage dataset in pandas. It might make sense to add that content directly at the end of the conditionals and functions episodes - something to keep in mind.

**Comment by chennesy** [comment]
@jt14den idea to make this new episode focus on data viz and tidy data cleaning of the lesson dataset. Should use conditionals and functions to work with the dataset in a way that pulls together key objectives from the lesson + plot interesting trends from the data.

**Comment by jt14den** [comment]
@chennesy, @scottcpeterson please take a look at a draft of this episode in collab https://colab.research.google.com/drive/13BGX1irZPCTdVxpYjWJz1x9I_s_7iGOd?usp=sharing. 
It needs: 

- proofreading and copyediting 
- decision if we want two episodes: one on tidy data/unpivoting and one on dataviz
- add the combined and long dfs to the lesson, so we have pick up points without going thru all the transformation and greater flexibility to jump around 

I can show part of this on Friday.
