### ISSUE TITLE
writing functions  Order of Operations  challenge

### ISSUE THREAD

**Issue by jt14den** [chennesy/lc-python-intro#50]
To me, this challenge will be confusing because it's not explained how the output prints the date and includes `result of the call is: None.` This is primarily because the function prints out the date and doesn't return anything, so not really getting at order of operation. 

The example above:
PYTHON
```
result = print_date(1871, 3, 19)
print(f'result of call is: {result}')
```

printed:
OUTPUT

```
1871/3/19
result of call is: None
```

Explain why the two lines of output appeared in the order they did.

SOLUTION: 
>Each line of Python code is executed in order, regardless of whether that line calls out to a function, which may call out to other functions, or a variable assignment. In this case, the second line call to print will not execute until the result of print_date is complete in the first line.

**Comment by chennesy** [comment]
This section can be deleted since None is introduced already in the built-in functions episode earlier on - I clarified the language there in PR #52. @jt14den, when you do the PR for issue #15, would you also delete this section from the episode? thanks!

**Comment by chennesy** [comment]
Challenge removed
