### ISSUE TITLE
Lists: change zip codes example

### ISSUE THREAD

**Issue by chennesy** [chennesy/lc-python-intro#70]
[The zip code list example](https://chennesy.github.io/lc-python-intro/lists.html#a-list-stores-many-values-in-a-single-structure.) in the Lists episode takes too long to type out and isn't a very meaningful example of how/why you'd use a list. It's also difficult to see the differences in the zip code list when they're edited. 

Change all of the zip code examples in the lesson to be a quicker and easier to understand list. Try metadata standards instead:

`metadata = ['marc', 'frbr', 'mets', 'mods']`

`print(f'metadata list was: {metadata}')`
`metadata[0] = 'bibframe'`
`print(f'metadata list is now: {metadata}')`

`metadata.append('oai-pmh')`

Keep the [primes example](https://chennesy.github.io/lc-python-intro/lists.html#use-del-to-remove-items-from-a-list-entirely.) since it uses numbers instead of strings.

**Comment by jt14den** [comment]
in jupyter you don't need the print() for the f string, it prints nicely without it
